/**
 * Single source of truth for all simulation constants.
 * Derived from GAME_MATH.md formulas.
 */
export const SIM_CONSTANTS = Object.freeze({
  // --- Energy Rates ---
  BASE_METABOLIC_RATE: 0.02,
  LIGNIN_BMR_REDUCTION: 0.8,
  RADIATION_PHOTO_PENALTY: 0.2,
  CANNIBALISM_RECOVERY: 0.5,
  HP_LOSS_PER_TICK: 5,

  // --- Storage ---
  STORAGE_BASE: 0.1,
  STORAGE_STEM_FACTOR: 0.5,
  STORAGE_DISTRIBUTION_FACTOR: 0.4,

  // --- Growth ---
  LIGNIN_GROWTH_MULTIPLIER: 5.0,
  DENSITY_GROWTH_MULTIPLIER: 2.0,
  BASE_GROWTH_INCREMENT: 0.05,

  // --- Reproduction ---
  PACKAGING_COST_FACTOR: 1.0,
  SUGAR_COST_FACTOR: 3.0,
  SIGNALING_COST_FACTOR: 0.5,
  REPRODUCTION_ENERGY_THRESHOLD: 0.7,
  REPRODUCTION_BIOMASS_THRESHOLD: 0.6,
  SEED_DORMANCY_TICKS: 10,
  SEED_BASE_HP: 20,
  SEED_INITIAL_ENERGY: 5,
  SEED_DISPERSAL_RADIUS: 2,

  // --- Trait Upkeep ---
  NITROGEN_FIXATION_COST: 0.1,
  TOXIN_UPKEEP_COST: 0.03,
  RADIATION_UPKEEP_COST: 0.01,

  // --- Environment ---
  EVAPORATION_RATE: 0.02,
  DRAINAGE_RATE: 0.01,
  RAIN_ABSORPTION_RATE: 0.1,
  DECOMPOSITION_RATE: 0.005,
  EROSION_ROOT_PROTECTION: 0.8,
  EROSION_BIOFILM_PROTECTION: 0.5,
  BIOFILM_DECAY_RATE: 0.002,
  BIOFILM_GROWTH_RATE: 0.005,
  TOXIN_DECAY_RATE: 0.01,
  NITROGEN_FIXATION_NUTRIENT_RATE: 0.03,
  SHADE_EVAPORATION_REDUCTION: 0.5,

  // --- Weather Defaults ---
  BASE_LIGHT: 0.7,
  LIGHT_AMPLITUDE: 0.3,
  BASE_RAIN: 0.3,
  RAIN_AMPLITUDE: 0.2,
  WEATHER_CYCLE_LENGTH: 200,
  BASE_WIND: 0.3,
  WIND_AMPLITUDE: 0.2,
  WIND_CYCLE_LENGTH: 150,

  // --- Flux Economy ---
  FLUX_RATE: 0.1,
  STARTING_FLUX: 100,
  STARTING_FLUX_CAP: 500,

  // --- Tool Effects ---
  TOOL_HYDRATE_AMOUNT: 0.2,
  TOOL_DESICCATE_AMOUNT: 0.2,
  TOOL_ENRICH_AMOUNT: 0.2,

  // --- Entity Defaults ---
  DEFAULT_HP: 100,
  DEFAULT_INITIAL_ENERGY: 10,
  DEFAULT_INITIAL_BIOMASS: 0.1,
  DEFAULT_INITIAL_WATER: 5,

  // --- Grid Defaults ---
  DEFAULT_WATER: 0.5,
  DEFAULT_NUTRIENTS: 0.3,
  DEFAULT_GRANULARITY: 0.5,
  DEFAULT_ORGANIC_SATURATION: 0.1,
  DEFAULT_SURFACE_ROUGHNESS: 0.5,

  // --- Derived Trait Scales ---
  LEAF_AREA_SCALE: 1.0,
  WATER_NEED_BASE: 0.5,
  WATER_NEED_SOLAR_FACTOR: 0.5,
  SHADE_CONTRIBUTION_SCALE: 0.3,
  ROOT_DENSITY_SCALE: 1.0,
  GROWTH_SPEED_BASE: 0.3,
  GROWTH_SPEED_LIGNIN_PENALTY: 0.7,

  // --- Water Consumption ---
  WATER_CONSUMPTION_RATE: 0.02,
  NUTRIENT_CONSUMPTION_RATE: 0.01,
});
